// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBdob95uq1_XWiSpJ-nmcCHOMH-pzsxz4',
    appId: '1:630320611531:web:8ce0daed525406ffd59b4e',
    messagingSenderId: '630320611531',
    projectId: 'paygo-assignment-752fe',
    authDomain: 'paygo-assignment-752fe.firebaseapp.com',
    storageBucket: 'paygo-assignment-752fe.appspot.com',
    measurementId: 'G-WRJHBYBZCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Huwsxy474OGooguddVkBp-v2NAkX5OI',
    appId: '1:630320611531:android:913e2fcfb0e9d45ad59b4e',
    messagingSenderId: '630320611531',
    projectId: 'paygo-assignment-752fe',
    storageBucket: 'paygo-assignment-752fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3W_5kgsFy9peodVn_C4YJlM2g_bvQOhg',
    appId: '1:630320611531:ios:df6452849486bfabd59b4e',
    messagingSenderId: '630320611531',
    projectId: 'paygo-assignment-752fe',
    storageBucket: 'paygo-assignment-752fe.appspot.com',
    iosBundleId: 'com.example.paygo_app',
  );

}